KeyCode Encryption
telamon/rant pull request #1
Opened 2022-09-27 17:04 UTC by Pingu1337

2022-09-27 22:33 UTC, telamon requested changes
General review Thumbs up, the initial feature is complete with minor fixes;

humble request, for the sake of project consistency try to use UpperCamel only for class names.

Good news, we have full TDD-support; Changes to `blockend/` can/should be developed using tests that don't require you to use the browser at all `yarn test`
and  `yarn debug`.
It'll be our only lifeline to sanity when network interactions gets thrown into the mix. 🤪

Please remove `package-json.lock` it's a very bad file :(
But to be fair I'm leaning towards discarding `yarn.lock` too..
(Something wierd happened to yarn's lockfile, did npm rewrite it? O_o)

##  This... Is... Brutally Awesome!
![image](https://user-images.githubusercontent.com/148454/192648102-0ac47551-6e23-401c-b2e1-bd79174b1876.png)


Thank you.

2022-09-28 11:50 UTC, Pingu1337 commented on frontend/components/keypad-dialog.js
> +      <div class='keypad'>
nope its on :61

2022-09-28 11:53 UTC, Pingu1337 commented on frontend/components/keypad-dialog.js
> +      return this.html`
This was my initial thought, i hardcoded it to be able to test the unlock feature. Will be looking into making a better looking solution with less code.

2022-09-28 11:53 UTC, Pingu1337 commented on frontend/components/message-preview.js
> +  async sleep (ms) {
yes, forgot to remove it during refactoring

2022-09-29 17:21 UTC, Pingu1337 commented on frontend/components/keypad-dialog.js
>  export async function promptPIN (text) {
An awaitable function that waits for user to input secret PIN before decrypting and returning the message to render.

2022-09-30 11:32 UTC, telamon approved these changes
Nice!
This was a big feature, in retrospect it would've been nice to split the keypad dialog component and blockend encryption into two separate PR's/features.

2022-09-30 13:32 UTC, merged